---

- name: Run acertmgr
  command: /usr/bin/acertmgr

- name: Restart powerdns
  service: name={{ item }} state=restarted
  with_items:
   - pdns
   - pdns-recursor

- name: Restart dnsdist
  service: name=dnsdist state=restarted
