---
# Select best time source
# * on kvm sync to hypervisor rtc within nanoseconds accuracy
# * on anything else use ntpd wich supports only milliseconds accuracy

- name: Setup chrony
  include_tasks: chrony.yml
  register: ntp_use_chrony
  when:
  - ansible_virtualization_role == 'guest'
  - ansible_virtualization_type == 'kvm'

- name: Setup ntpd
  include_tasks: ntp.yml
  when:
  - ntp_use_chrony is skipped
