---

- name: Reload systemd
  systemd: daemon_reload=yes

- name: Restart yanic
  service: name=yanic state=restarted

- name: Restart yanic-publish
  service: name=yanic-publish.timer state=restarted
