---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - common
  - apt
  - ntp
  - node_exporter

- name: Setup gateway servers
  hosts: [gw11.regensburg.freifunk.net, gw21.regensburg.freifunk.net, gw31.regensburg.freifunk.net, gw12.regensburg.freifunk.net, gw22.regensburg.freifunk.net]
  roles:
  - root_keys
  - arp_cache
  - batman
  - bird
  - fastd
  - fastd_exporter
  - interfaces
  - exit_ip
  - dns
  - radvd
  - dhcpd
  - respondd
  - yanic
  - web_gw

- name: Setup name servers
  hosts: ns1.regensburg.freifunk.net
  roles:
  - dns_auth

- name: Setup web service proxy
  hosts: web.regensburg.freifunk.net
  roles:
  - web_svc

- name: Setup stats server
  hosts: stats.ffrgb
  roles:
  - prometheus
  - grafana

- name: Setup unms server
  hosts: unms.ffrgb
  roles:
  - docker

- name: Setup unifi server
  hosts: unifi.ffrgb
  roles:
  - unifi

- name: Setup tile server
  hosts: tiles.ffrgb
  roles:
  - tileserver

- name: Setup netbox server
  hosts: netbox.ffrgb
  roles:
  - netbox
