---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - common
  - apt
  - ntp

- name: Setup gateway servers
  hosts: [gw11.regensburg.freifunk.net, gw21.regensburg.freifunk.net, gw31.regensburg.freifunk.net]
  roles:
  - batman
  - fastd
  - mesh-interfaces
  - exit-ipv4
  - dns
  - dhcpd
  - respondd
  - yanic
  - web-gw

- name: Setup confluence server
  hosts: confluence.regensburg.freifunk.net
  roles:
  - confluence
