---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - common
  - apt
  - ntp

- name: Setup gateway servers
  hosts: gw31.regensburg.freifunk.net
  roles:
  - batman
  - fastd
  - mesh-interfaces
  - dns
  - dhcpd
  - respondd

- name: Setup confluence server
  hosts: confluence.regensburg.freifunk.net
  roles:
  - confluence
