---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - common
  - apt
  - ntp
  - node_exporter

- name: Setup gateway servers
  hosts: [gw11.regensburg.freifunk.net, gw21.regensburg.freifunk.net, gw31.regensburg.freifunk.net, gw12.regensburg.freifunk.net, gw22.regensburg.freifunk.net]
  roles:
  - gw-admin-ssh-keys
  - arp-cache
  - batman
  - bird
  - fastd
  - fastd-exporter
  - mesh-interfaces
  - exit-ip
  - dns
  - radvd
  - dhcpd
  - respondd
  - yanic
  - web-gw

- name: Setup web service proxy
  hosts: web.regensburg.freifunk.net
  roles:
  - web-svc

- name: Setup stats server
  hosts: stats.ffrgb
  roles:
  - prometheus
  - grafana

- name: Setup docker servers
  hosts: [unms.ffrgb, unifi.ffrgb, tiles.ffrgb]
  roles:
  - docker

- name: Setup tile server
  hosts: tiles.ffrgb
  roles:
  - tileserver
