---

- name: Install dhcp server
  apt: name=isc-dhcp-server state=latest

- name: Configure dhcp server
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
  notify: Restart isc-dhcp-server

- name: Start the dhcp server
  service: name=isc-dhcp-server state=started enabled=yes
