---

- name: Install dependencies
  apt:
    name:
    - bridge-utils
    - python-pkg-resources

# work-around to get a version new enough not to screw up forwarding setting on all interfaces
- name: Install ifupdown2
  apt: deb=http://ftp.de.debian.org/debian/pool/main/i/ifupdown2/ifupdown2_3.0.0-1_all.deb

- name: Uninstall ifupdown
  apt: name=ifupdown state=absent

# this is required for nginx, dhcpd and other to start correctly
# see https://github.com/CumulusNetworks/ifupdown2/issues/30#issuecomment-360589850
- name: Install fixed networking.service file
  copy: src=networking.service dest=/lib/systemd/system/networking.service
  notify: Reload systemd

- name: Configure mesh interfaces
  template: src=mesh.conf.j2 dest=/etc/network/interfaces.d/mesh.conf
  notify: Reload interfaces

- name: Configure backbone interfaces
  template: src=backbone.conf.j2 dest=/etc/network/interfaces.d/backbone.conf
  notify: Reload interfaces
