---

certmgr_mode: webserver

ntp_servers:
- 0.de.pool.ntp.org
- 1.de.pool.ntp.org
- 2.de.pool.ntp.org
- 3.de.pool.ntp.org

confluence_domain: confluence.regensburg.freifunk.net
confluence_dbname: confluence
confluence_dbuser: confluence
confluence_dbpass: "{{ vault_confluence_dbpass }}"
