---

acertmgr_mode: webdir

fastd_targets:
- gw11.regensburg.freifunk.net:9281
- gw21.regensburg.freifunk.net:9281
- gw31.regensburg.freifunk.net:9281

gre_prefix: 10.90.232.0/24
gre_matrix:
# - { id: 1, a: svcs, b: gw11 }
# - { id: 2, a: svcs, b: gw12 }
# - { id: 3, a: svcs, b: gw21 }
# - { id: 4, a: svcs, b: gw22 }
# - { id: 5, a: svcs, b: gw31 }
# - { id: 9, a: gw11, b: gw12 }
 - { id: 10, a: gw11, b: gw21 }
# - { id: 11, a: gw11, b: gw22 }
 - { id: 12, a: gw11, b: gw31 }
# - { id: 17, a: gw12, b: gw21 }
# - { id: 18, a: gw12, b: gw22 }
# - { id: 19, a: gw12, b: gw31 }
# - { id: 25, a: gw21, b: gw22 }
 - { id: 26, a: gw21, b: gw31 }
# - { id: 33, a: gw22, b: gw31 }

netbox_domain: netbox.ffrgb
netbox_dbname: netbox
netbox_dbuser: netbox
netbox_dbpass: "{{ vault_netbox_dbpass }}"
netbox_secret: "{{ vault_netbox_secret }}"

node_targets:
- gw11.regensburg.freifunk.net:9100
- gw21.regensburg.freifunk.net:9100
- gw31.regensburg.freifunk.net:9100
- ns1.regensburg.freifunk.net:9100
- stats.regensburg.freifunk.net:9100
- web.regensburg.freifunk.net:9100
- stats.ffrgb:9100
- unms.ffrgb:9100
- unifi.ffrgb:9100
- tiles.ffrgb:9100
- netbox.ffrgb:9100

ntp_servers:
- 0.de.pool.ntp.org
- 1.de.pool.ntp.org
- 2.de.pool.ntp.org
- 3.de.pool.ntp.org

prometheus_node_pass: "{{ vault_prometheus_node_pass }}"

prometheus_pve_user: prometheus@pve
prometheus_pve_pass: "{{ vault_prometheus_pve_pass }}"

pve_targets:
- pve01.ffrgb
- pve02.ffrgb

site: ffrgb
site_domain: regensburg.freifunk.net

web_services:
- { id: tiles, domain: tiles.regensburg.freifunk.net }
