---

- name: Install dependencies
  apt: name={{ item }}
  with_items:
  - git
  - python-cryptography
  - python-dnspython
  - python-yaml

- name: Install acertmgr
  git: repo=https://github.com/moepman/acertmgr.git dest=/opt/acertmgr depth=1 version={{ acertmgr_version }}

- name: Create config directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - /etc/acme
  - /etc/acme/domains.d

- name: Configure acertmgr
  template: src=acme.conf.j2 dest=/etc/acme/acme.conf

- name: Create challenge directory
  file: path=/var/www/acme-challenge/ owner=root mode=0755 state=directory

- name: Enable acertmgr cronjob
  cron: name=certmgr special_time=daily job=/opt/acertmgr/acertmgr.py
