---

yanic_source: github.com/ffrgb/yanic

yanic_publisher: false

yanic_respondd_enable: true
yanic_respondd_collect_interval: 1m
yanic_respondd_synchronize_interval: 1m

yanic_respondd_interface: br-{{ site_code }}
yanic_respondd_ip: false

yanic_webserver: false
yanic_webserver_bind: "127.0.0.1:8080"
yanic_webserver_webroot: "/var/www/html/meshviewer"

yanic_nodes: true
yanic_nodes_state_path: "/var/lib/yanic/yanic.json"
yanic_nodes_prune_after: 7d
yanic_nodes_save_interval: 5s
yanic_nodes_offline_after: 10m

yanic_meshviewer_ffrgb_enable: true
yanic_meshviewer_ffrgb_path: "/var/www/html/meshviewer/data/meshviewer.json"

yanic_meshviewer_enable: true
yanic_meshviewer_version: 2
yanic_meshviewer_path: "/var/www/html/meshviewer/data"
yanic_meshviewer_nodes: "{{ yanic_meshviewer_path }}/nodes.json"
yanic_meshviewer_graph: "{{ yanic_meshviewer_path }}/graph.json"

yanic_nodelist_enable: false

yanic_database_delete_after: 7d
yanic_database_delete_interval: 1h

yanic_influxdb:
- enable: false
  host: http://127.0.0.1:8086
  database: ffrgb
  username: ""
  password: ""

yanic_graphite:
- enable: false
  address: "localhost:2003"
  prefix: "freifunk"

yanic_dbc_repondd_enable: true
yanic_dbc_repondd_remotehost: "stats.regensburg.freifunk.net:10001"
