---

- name: Install dependencies
  apt: name=python-pkg-resources

- name: Install ifupdown2
  apt: name=ifupdown2 state=latest

- name: Uninstall ifupdown
  apt: name=ifupdown state=absent

- name: Configure mesh interfaces
  template: src=mesh.conf.j2 dest=/etc/network/interfaces.d/mesh.conf
  notify: Reload interfaces

- name: Configure backbone interfaces
  template: src=backbone.conf.j2 dest=/etc/network/interfaces.d/backbone.conf
  notify: Reload interfaces
