---

- name: Install prometheus
  apt: name=prometheus

- name: Configure prometheus
  template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Enable prometheus
  service: name=prometheus state=started enabled=yes
