---

- name: Cleanup
  apt: autoclean=yes
  when: ansible_os_family == 'Debian'

- name: Gather package facts
  package_facts:
    manager: apt
  when: ansible_os_family == 'Debian'

- name: Proxmox
  include: Proxmox.yml
  when: ansible_os_family == 'Debian' and 'pve-manager' in ansible_facts.packages

- name: Debian
  include: Debian.yml
  when: ansible_os_family == 'Debian' and 'pve-manager' not in ansible_facts.packages

- name: FreeBSD
  include: FreeBSD.yml
  when: ansible_distribution == 'FreeBSD'
