---

- name: Enable docker apt-key
  apt_key: url='https://download.docker.com/linux/debian/gpg'

- name: Enable docker repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/debian buster stable'
    filename: docker

- name: Install docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python-docker
