---

- name: Install batctl
  apt: name=batctl state=latest

- name: Enable batman during boot
  lineinfile: dest=/etc/modules line=batman-adv

- name: Load batman-adv module
  modprobe: name=batman-adv
