---

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart prometheus
  service: name=prometheus state=restarted

- name: Restart prometheus-pve-exporter
  service: name=prometheus-pve-exporter state=restarted
