---

- name: Install dependencies
  apt: name=ethtool

- name: Clone respondd announce repository
  git: repo={{ respondd_announce_git_root }} dest=/opt/{{ site_code }}/respondd-announce/
  notify: Restart respondd

- name: Install system unit
  template: src=respondd.service.j2 dest=/lib/systemd/system/respondd.service
  notify:
  - Reload systemd
  - Restart respondd

- name: Enable respondd
  service: name=respondd enabled=yes
